# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoprice',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cargoprice',
            name='quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billNo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerAddress',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customerPhone',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trackNo',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='userid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='soldcount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='ord_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='pro_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='nil', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='nil', max_length=30),
        ),
    ]
