# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0003_auto_20170510_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
