# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_auto_20170521_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productorder', to='product.Product'),
        ),
    ]
