# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0010_auto_20170523_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoprice',
            name='name',
            field=models.CharField(default='N', max_length=3, null=True),
        ),
    ]
