# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='nil', max_length=30, null=True)),
                ('username', models.CharField(default='nil', max_length=30, null=True)),
                ('password', models.CharField(default='nil', max_length=30, null=True)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
    ]
