# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('userid', models.IntegerField(default=0, null=True)),
                ('trackNo', models.IntegerField(default=0, null=True)),
                ('billNo', models.IntegerField(default=0, null=True)),
                ('customerAddress', models.CharField(default='nil', max_length=30, null=True)),
                ('customerPhone', models.CharField(default='nil', max_length=30, null=True)),
            ],
        ),
    ]
