# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='totalprice',
        ),
        migrations.AddField(
            model_name='order',
            name='totalquantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
