# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170521_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerPhone',
            new_name='customerName',
        ),
        migrations.AddField(
            model_name='order',
            name='customerSurname',
            field=models.CharField(default='nil', max_length=30, null=True),
        ),
    ]
